/// @copyright 2022 ECCI, Universidad de Costa Rica. All rights reserved
/// @author Michelle Fonseca Carrillo <michelle.fonsecacarrillo@ucr.ac.cr>
/// @author Esteban Castañeda Blanco <esteban.castaneda@ucr.ac.cr>
/// @author Daniel Lizano Morales <daniel.lizanomorales@ucr.ac.cr>
/// @author Jorge Loría López <jorge.lorialopez@ucr.ac.cr>
/// This code is released under the GNU Public License version 3

#ifndef COUNTRYCODES_HPP
#define COUNTRYCODES_HPP

#include <map>

class CountryCodes
{
  std::map<std::string, std::string> countries;

  CountryCodes::CountryCodes()
  {
    this->countries.insert({"Afghanistan", "AFG"});
    this->countries.insert({"Afghanistan", "AFG"});
    this->countries.insert({"Albania", "ALB"});
    this->countries.insert({"Algeria", "ALG"});
    this->countries.insert({"American Samoa", "ASA"});
    this->countries.insert({"Andorra", "AND"});
    this->countries.insert({"Angola", "ANG"});
    this->countries.insert({"Anguilla", "AIA"});
    this->countries.insert({"Antigua and Barbuda", "ATG"});
    this->countries.insert({"Argentina", "ARG"});
    this->countries.insert({"Armenia", "ARM"});
    this->countries.insert({"Aruba", "ARU"});
    this->countries.insert({"Australia", "AUS"});
    this->countries.insert({"Austria", "AUT"});
    this->countries.insert({"Azerbaijan", "AZE"});
    this->countries.insert({"Bahamas", "BAH"});
    this->countries.insert({"Bahrain", "BHR"});
    this->countries.insert({"Bangladesh", "BAN"});
    this->countries.insert({"Barbados", "BRB"});
    this->countries.insert({"Belarus", "BLR"});
    this->countries.insert({"Belgium", "BEL"});
    this->countries.insert({"Belize", "BLZ"});
    this->countries.insert({"Benin", "BEN"});
    this->countries.insert({"Bermuda", "BER"});
    this->countries.insert({"Bhutan", "BHU"});
    this->countries.insert({"Bolivia", "BOL"});
    this->countries.insert({"Bosnia and Herzegovina", "BIH"});
    this->countries.insert({"Botswana", "BOT"});
    this->countries.insert({"Brazil", "BRA"});
    this->countries.insert({"British Virgin Islands", "VGB"});
    this->countries.insert({"Brunei", "BRU"});
    this->countries.insert({"Bulgaria", "BUL"});
    this->countries.insert({"Burkina Faso", "BFA"});
    this->countries.insert({"Burundi", "BDI"});
    this->countries.insert({"Cambodia", "CAM"});
    this->countries.insert({"Cameroon", "CMR"});
    this->countries.insert({"Canada", "CAN"});
    this->countries.insert({"Cape Verde", "CPV"});
    this->countries.insert({"Cayman Islands", "CAY"});
    this->countries.insert({"Central African Republic", "CTA"});
    this->countries.insert({"Chad", "CHA"});
    this->countries.insert({"Chile", "CHI"});
    this->countries.insert({"China", "CHN"});
    this->countries.insert({"Chinese Taipei", "TPE"});
    this->countries.insert({"Colombia", "COL"});
    this->countries.insert({"Comoros", "COM"});
    this->countries.insert({"Congo", "CGO"});
    this->countries.insert({"Cook Islands", "COK"});
    this->countries.insert({"Costa Rica", "CRC"});
    this->countries.insert({"Croatia", "CRO"});
    this->countries.insert({"Cuba", "CUB"});
    this->countries.insert({"Curaçao", "CUW"});
    this->countries.insert({"Cyprus", "CYP"});
    this->countries.insert({"Czech Republic", "CZE"});
    this->countries.insert({"Denmark", "DEN"});
    this->countries.insert({"Djibouti", "DJI"});
    this->countries.insert({"Dominica", "DMA"});
    this->countries.insert({"Dominican Republic", "DOM"});
    this->countries.insert({"DR Congo", "COD"});
    this->countries.insert({"Ecuador", "ECU"});
    this->countries.insert({"Egypt", "EGY"});
    this->countries.insert({"El Salvador", "SLV"});
    this->countries.insert({"England", "ENG"});
    this->countries.insert({"Equatorial Guinea", "EQG"});
    this->countries.insert({"Eritrea", "ERI"});
    this->countries.insert({"Estonia", "EST"});
    this->countries.insert({"Eswatini", "SWZ"});
    this->countries.insert({"Ethiopia", "ETH"});
    this->countries.insert({"Faroe Islands", "FRO"});
    this->countries.insert({"Fiji", "FIJ"});
    this->countries.insert({"Finland", "FIN"});
    this->countries.insert({"France", "FRA"});
    this->countries.insert({"Gabon", "GAB"});
    this->countries.insert({"Gambia", "GAM"});
    this->countries.insert({"Georgia", "GEO"});
    this->countries.insert({"Germany", "GER"});
    this->countries.insert({"Ghana", "GHA"});
    this->countries.insert({"Gibraltar", "GIB"});
    this->countries.insert({"Greece", "GRE"});
    this->countries.insert({"Grenada", "GRN"});
    this->countries.insert({"Guam", "GUM"});
    this->countries.insert({"Guatemala", "GUA"});
    this->countries.insert({"Guinea", "GUI"});
    this->countries.insert({"Guinea - Bissau", "GNB"});
    this->countries.insert({"Guyana", "GUY"});
    this->countries.insert({"Haiti", "HAI"});
    this->countries.insert({"Honduras", "HON"});
    this->countries.insert({"Hong Kong", "HKG"});
    this->countries.insert({"Hungary", "HUN"});
    this->countries.insert({"Iceland", "ISL"});
    this->countries.insert({"India", "IND"});
    this->countries.insert({"Indonesia", "IDN"});
    this->countries.insert({"Iran", "IRN"});
    this->countries.insert({"Iraq", "IRQ"});
    this->countries.insert({"Israel", "ISR"});
    this->countries.insert({"Italy", "ITA"});
    this->countries.insert({"Ivory Coast", "CIV"});
    this->countries.insert({"Jamaica", "JAM"});
    this->countries.insert({"Japan", "JPN"});
    this->countries.insert({"Jordan", "JOR"});
    this->countries.insert({"Kazakhstan", "KAZ"});
    this->countries.insert({"Kenya", "KEN"});
    this->countries.insert({"Kosovo", "KOS"});
    this->countries.insert({"Kuwait", "KUW"});
    this->countries.insert({"Kyrgyzstan", "KGZ"});
    this->countries.insert({"Laos", "LAO"});
    this->countries.insert({"Latvia", "LVA"});
    this->countries.insert({"Lebanon", "LBN"});
    this->countries.insert({"Lesotho", "LES"});
    this->countries.insert({"Liberia", "LBR"});
    this->countries.insert({"Libya", "LBY"});
    this->countries.insert({"Liechtenstein", "LIE"});
    this->countries.insert({"Lithuania", "LTU"});
    this->countries.insert({"Luxembourg", "LUX"});
    this->countries.insert({"Macau", "MAC"});
    this->countries.insert({"Madagascar", "MAD"});
    this->countries.insert({"Malawi", "MWI"});
    this->countries.insert({"Malaysia", "MAS"});
    this->countries.insert({"Maldives", "MDV"});
    this->countries.insert({"Mali", "MLI"});
    this->countries.insert({"Malta", "MLT"});
    this->countries.insert({"Mauritania", "MTN"});
    this->countries.insert({"Mauritius", "MRI"});
    this->countries.insert({"Mexico", "MEX"});
    this->countries.insert({"Moldova", "MDA"});
    this->countries.insert({"Mongolia", "MNG"});
    this->countries.insert({"Montenegro", "MNE"});
    this->countries.insert({"Montserrat", "MSR"});
    this->countries.insert({"Morocco", "MAR"});
    this->countries.insert({"Mozambique", "MOZ"});
    this->countries.insert({"Myanmar", "MYA"});
    this->countries.insert({"Namibia", "NAM"});
    this->countries.insert({"Nepal", "NEP"});
    this->countries.insert({"Netherlands", "NED"});
    this->countries.insert({"New Caledonia", "NCL"});
    this->countries.insert({"New Zealand", "NZL"});
    this->countries.insert({"Nicaragua", "NCA"});
    this->countries.insert({"Niger", "NIG"});
    this->countries.insert({"Nigeria", "NGA"});
    this->countries.insert({"North Korea", "PRK"});
    this->countries.insert({"North Macedonia", "MKD"});
    this->countries.insert({"Northern Ireland", "NIR"});
    this->countries.insert({"Norway", "NOR"});
    this->countries.insert({"Oman", "OMA"});
    this->countries.insert({"Pakistan", "PAK"});
    this->countries.insert({"Palestine", "PLE"});
    this->countries.insert({"Panama", "PAN"});
    this->countries.insert({"Papua New Guinea", "PNG"});
    this->countries.insert({"Paraguay", "PAR"});
    this->countries.insert({"Peru", "PER"});
    this->countries.insert({"Philippines", "PHI"});
    this->countries.insert({"Poland", "POL"});
    this->countries.insert({"Portugal", "POR"});
    this->countries.insert({"Puerto Rico", "PUR"});
    this->countries.insert({"Qatar", "QAT"});
    this->countries.insert({"Republic of Ireland", "IRL"});
    this->countries.insert({"Romania", "ROU"});
    this->countries.insert({"Russia", "RUS"});
    this->countries.insert({"Rwanda", "RWA"});
    this->countries.insert({"Saint Kitts and Nevis", "SKN"});
    this->countries.insert({"Saint Lucia", "LCA"});
    this->countries.insert({"Saint Vincent and the Grenadines", "VIN"});
    this->countries.insert({"Samoa", "SAM"});
    this->countries.insert({"San Marino", "SMR"});
    this->countries.insert({"São Tomé and Príncipe", "STP"});
    this->countries.insert({"Saudi Arabia", "KSA"});
    this->countries.insert({"Scotland", "SCO"});
    this->countries.insert({"Senegal", "SEN"});
    this->countries.insert({"Serbia", "SRB"});
    this->countries.insert({"Seychelles", "SEY"});
    this->countries.insert({"Sierra Leone", "SLE"});
    this->countries.insert({"Singapore", "SGP"});
    this->countries.insert({"Slovakia", "SVK"});
    this->countries.insert({"Slovenia", "SVN"});
    this->countries.insert({"Solomon Islands", "SOL"});
    this->countries.insert({"Somalia", "SOM"});
    this->countries.insert({"South Africa", "RSA"});
    this->countries.insert({"South Korea", "KOR"});
    this->countries.insert({"South Sudan", "SSD"});
    this->countries.insert({"Spain", "ESP"});
    this->countries.insert({"Sri Lanka", "SRI"});
    this->countries.insert({"Sudan", "SDN"});
    this->countries.insert({"Suriname", "SUR"});
    this->countries.insert({"Sweden", "SWE"});
    this->countries.insert({"Switzerland", "SUI"});
    this->countries.insert({"Syria", "SYR"});
    this->countries.insert({"Tahiti", "TAH"});
    this->countries.insert({"Tajikistan", "TJK"});
    this->countries.insert({"Tanzania", "TAN"});
    this->countries.insert({"Thailand", "THA"});
    this->countries.insert({"Timor - Leste", "TLS"});
    this->countries.insert({"Togo", "TOG"});
    this->countries.insert({"Tonga", "TGA"});
    this->countries.insert({"Trinidad and Tobago", "TRI"});
    this->countries.insert({"Tunisia", "TUN"});
    this->countries.insert({"Turkey", "TUR"});
    this->countries.insert({"Turkmenistan", "TKM"});
    this->countries.insert({"Turks and Caicos Islands", "TCA"});
    this->countries.insert({"Uganda", "UGA"});
    this->countries.insert({"Ukraine", "UKR"});
    this->countries.insert({"United Arab Emirates", "UAE"});
    this->countries.insert({"United States", "USA"});
    this->countries.insert({"Uruguay", "URU"});
    this->countries.insert({"U.S.Virgin Islands", "VIR"});
    this->countries.insert({"Uzbekistan", "UZB"});
    this->countries.insert({"Vanuatu", "VAN"});
    this->countries.insert({"Venezuela", "VEN"});
    this->countries.insert({"Vietnam", "VIE"});
    this->countries.insert({"Wales", "WAL"});
    this->countries.insert({"Yemen", "YEM"});
    this->countries.insert({"Zambia", "ZAM"});
    this->countries.insert({"Zimbabwe", "ZIM"});
  };
};

#endif // !COUNTRYCODES_HPP
