/// @copyright 2022 ECCI, Universidad de Costa Rica. All rights reserved
/// @author Michelle Fonseca Carrillo <michelle.fonsecacarrillo@ucr.ac.cr>
/// @author Esteban Castañeda Blanco <esteban.castaneda@ucr.ac.cr>
/// @author Daniel Lizano Morales <daniel.lizanomorales@ucr.ac.cr>
/// @author Jorge Loría López <jorge.lorialopez@ucr.ac.cr>
/// This code is released under the GNU Public License version 3

#ifndef _COUNTRY_CODES_
#define _COUNTRY_CODES_

#include <map>
#include <iostream>

class CountryCodes {
  /// Array with tha countries
  std::map<std::string, std::string> countries;

  /**
   * @brief Constructor
   */
  CountryCodes::CountryCodes() {
    this->countries.insert({"AFG", "Afghanistan"});
    this->countries.insert({"ALB", "Albania"});
    this->countries.insert({"ALG", "Algeria"});
    this->countries.insert({"ASA", "American Samoa"});
    this->countries.insert({"AND", "Andorra"});
    this->countries.insert({"ANG", "Angola"});
    this->countries.insert({"AIA", "Anguilla"});
    this->countries.insert({"ATG", "Antigua and Barbuda"});
    this->countries.insert({"ARG", "Argentina"});
    this->countries.insert({"ARM", "Armenia"});
    this->countries.insert({"ARU", "Aruba"});
    this->countries.insert({"AUS", "Australia"});
    this->countries.insert({"AUT", "Austria"});
    this->countries.insert({"AZE", "Azerbaijan"});
    this->countries.insert({"BAH", "Bahamas"});
    this->countries.insert({"BHR", "Bahrain"});
    this->countries.insert({"BAN", "Bangladesh"});
    this->countries.insert({"BRB", "Barbados"});
    this->countries.insert({"BLR", "Belarus"});
    this->countries.insert({"BEL", "Belgium"});
    this->countries.insert({"BLZ", "Belize"});
    this->countries.insert({"BEN", "Benin"});
    this->countries.insert({"BER", "Bermuda"});
    this->countries.insert({"BHU", "Bhutan"});
    this->countries.insert({"BOL", "Bolivia"});
    this->countries.insert({"BIH", "Bosnia and Herzegovina"});
    this->countries.insert({"BOT", "Botswana"});
    this->countries.insert({"BRA", "Brazil"});
    this->countries.insert({"VGB", "British Virgin Islands"});
    this->countries.insert({"BRU", "Brunei"});
    this->countries.insert({"BUL", "Bulgaria"});
    this->countries.insert({"BFA", "Burkina Faso"});
    this->countries.insert({"BDI", "Burundi"});
    this->countries.insert({"CAM", "Cambodia"});
    this->countries.insert({"CMR", "Cameroon"});
    this->countries.insert({"CAN", "Canada"});
    this->countries.insert({"CPV", "Cape Verde"});
    this->countries.insert({"CAY", "Cayman Islands"});
    this->countries.insert({"CTA", "Central African Republic"});
    this->countries.insert({"CHA", "Chad"});
    this->countries.insert({"CHI", "Chile"});
    this->countries.insert({"CHN", "China"});
    this->countries.insert({"TPE", "Chinese Taipei"});
    this->countries.insert({"COL", "Colombia"});
    this->countries.insert({"COM", "Comoros"});
    this->countries.insert({"CGO", "Congo"});
    this->countries.insert({"COK", "Cook Islands"});
    this->countries.insert({"CRC", "Costa Rica"});
    this->countries.insert({"CRO", "Croatia"});
    this->countries.insert({"CUB", "Cuba"});
    this->countries.insert({"CUW", "Curaçao"});
    this->countries.insert({"CYP", "Cyprus"});
    this->countries.insert({"CZE", "Czech Republic"});
    this->countries.insert({"DEN", "Denmark"});
    this->countries.insert({"DJI", "Djibouti"});
    this->countries.insert({"DMA", "Dominica"});
    this->countries.insert({"DOM", "Dominican Republic"});
    this->countries.insert({"COD", "DR Congo"});
    this->countries.insert({"ECU", "Ecuador"});
    this->countries.insert({"EGY", "Egypt"});
    this->countries.insert({"SLV", "El Salvador"});
    this->countries.insert({"ENG", "England"});
    this->countries.insert({"EQG", "Equatorial Guinea"});
    this->countries.insert({"ERI", "Eritrea"});
    this->countries.insert({"EST", "Estonia"});
    this->countries.insert({"SWZ", "Eswatini"});
    this->countries.insert({"ETH", "Ethiopia"});
    this->countries.insert({"FRO", "Faroe Islands"});
    this->countries.insert({"FIJ", "Fiji"});
    this->countries.insert({"FIN", "Finland"});
    this->countries.insert({"FRA", "France"});
    this->countries.insert({"GAB", "Gabon"});
    this->countries.insert({"GAM", "Gambia"});
    this->countries.insert({"GEO", "Georgia"});
    this->countries.insert({"GER", "Germany"});
    this->countries.insert({"GHA", "Ghana"});
    this->countries.insert({"GIB", "Gibraltar"});
    this->countries.insert({"GRE", "Greece"});
    this->countries.insert({"GRN", "Grenada"});
    this->countries.insert({"GUM", "Guam"});
    this->countries.insert({"GUA", "Guatemala"});
    this->countries.insert({"GUI", "Guinea"});
    this->countries.insert({"GNB", "Guinea - Bissau"});
    this->countries.insert({"GUY", "Guyana"});
    this->countries.insert({"HAI", "Haiti"});
    this->countries.insert({"HON", "Honduras"});
    this->countries.insert({"HKG", "Hong Kong"});
    this->countries.insert({"HUN", "Hungary"});
    this->countries.insert({"ISL", "Iceland"});
    this->countries.insert({"IND", "India"});
    this->countries.insert({"IDN", "Indonesia"});
    this->countries.insert({"IRN", "Iran"});
    this->countries.insert({"IRQ", "Iraq"});
    this->countries.insert({"ISR", "Israel"});
    this->countries.insert({"ITA", "Italy"});
    this->countries.insert({"CIV", "Ivory Coast"});
    this->countries.insert({"JAM", "Jamaica"});
    this->countries.insert({"JPN", "Japan"});
    this->countries.insert({"JOR", "Jordan"});
    this->countries.insert({"KAZ", "Kazakhstan"});
    this->countries.insert({"KEN", "Kenya"});
    this->countries.insert({"KOS", "Kosovo"});
    this->countries.insert({"KUW", "Kuwait"});
    this->countries.insert({"KGZ", "Kyrgyzstan"});
    this->countries.insert({"LAO", "Laos"});
    this->countries.insert({"LVA", "Latvia"});
    this->countries.insert({"LBN", "Lebanon"});
    this->countries.insert({"LES", "Lesotho"});
    this->countries.insert({"LBR", "Liberia"});
    this->countries.insert({"LBY", "Libya"});
    this->countries.insert({"LIE", "Liechtenstein"});
    this->countries.insert({"LTU", "Lithuania"});
    this->countries.insert({"LUX", "Luxembourg"});
    this->countries.insert({"MAC", "Macau"});
    this->countries.insert({"MAD", "Madagascar"});
    this->countries.insert({"MWI", "Malawi"});
    this->countries.insert({"MAS", "Malaysia"});
    this->countries.insert({"MDV", "Maldives"});
    this->countries.insert({"MLI", "Mali"});
    this->countries.insert({"MLT", "Malta"});
    this->countries.insert({"MTN", "Mauritania"});
    this->countries.insert({"MRI", "Mauritius"});
    this->countries.insert({"MEX", "Mexico"});
    this->countries.insert({"MDA", "Moldova"});
    this->countries.insert({"MNG", "Mongolia"});
    this->countries.insert({"MNE", "Montenegro"});
    this->countries.insert({"MSR", "Montserrat"});
    this->countries.insert({"MAR", "Morocco"});
    this->countries.insert({"MOZ", "Mozambique"});
    this->countries.insert({"MYA", "Myanmar"});
    this->countries.insert({"NAM", "Namibia"});
    this->countries.insert({"NEP", "Nepal"});
    this->countries.insert({"NED", "Netherlands"});
    this->countries.insert({"NCL", "New Caledonia"});
    this->countries.insert({"NZL", "New Zealand"});
    this->countries.insert({"NCA", "Nicaragua"});
    this->countries.insert({"NIG", "Niger"});
    this->countries.insert({"NGA", "Nigeria"});
    this->countries.insert({"PRK", "North Korea"});
    this->countries.insert({"MKD", "North Macedonia"});
    this->countries.insert({"NIR", "Northern Ireland"});
    this->countries.insert({"NOR", "Norway"});
    this->countries.insert({"OMA", "Oman"});
    this->countries.insert({"PAK", "Pakistan"});
    this->countries.insert({"PLE", "Palestine"});
    this->countries.insert({"PAN", "Panama"});
    this->countries.insert({"PNG", "Papua New Guinea"});
    this->countries.insert({"PAR", "Paraguay"});
    this->countries.insert({"PER", "Peru"});
    this->countries.insert({"PHI", "Philippines"});
    this->countries.insert({"POL", "Poland"});
    this->countries.insert({"POR", "Portugal"});
    this->countries.insert({"PUR", "Puerto Rico"});
    this->countries.insert({"QAT", "Qatar"});
    this->countries.insert({"IRL", "Republic of Ireland"});
    this->countries.insert({"ROU", "Romania"});
    this->countries.insert({"RUS", "Russia"});
    this->countries.insert({"RWA", "Rwanda"});
    this->countries.insert({"SKN", "Saint Kitts and Nevis"});
    this->countries.insert({"LCA", "Saint Lucia"});
    this->countries.insert({"VIN", "Saint Vincent and the Grenadines"});
    this->countries.insert({"SAM", "Samoa"});
    this->countries.insert({"SMR", "San Marino"});
    this->countries.insert({"STP", "São Tomé and Príncipe"});
    this->countries.insert({"KSA", "Saudi Arabia"});
    this->countries.insert({"SCO", "Scotland"});
    this->countries.insert({"SEN", "Senegal"});
    this->countries.insert({"SRB", "Serbia"});
    this->countries.insert({"SEY", "Seychelles"});
    this->countries.insert({"SLE", "Sierra Leone"});
    this->countries.insert({"SGP", "Singapore"});
    this->countries.insert({"SVK", "Slovakia"});
    this->countries.insert({"SVN", "Slovenia"});
    this->countries.insert({"SOL", "Solomon Islands"});
    this->countries.insert({"SOM", "Somalia"});
    this->countries.insert({"RSA", "South Africa"});
    this->countries.insert({"KOR", "South Korea"});
    this->countries.insert({"SSD", "South Sudan"});
    this->countries.insert({"ESP", "Spain"});
    this->countries.insert({"SRI", "Sri Lanka"});
    this->countries.insert({"SDN", "Sudan"});
    this->countries.insert({"SUR", "Suriname"});
    this->countries.insert({"SWE", "Sweden"});
    this->countries.insert({"SUI", "Switzerland"});
    this->countries.insert({"SYR", "Syria"});
    this->countries.insert({"TAH", "Tahiti"});
    this->countries.insert({"TJK", "Tajikistan"});
    this->countries.insert({"TAN", "Tanzania"});
    this->countries.insert({"THA", "Thailand"});
    this->countries.insert({"TLS", "Timor - Leste"});
    this->countries.insert({"TOG", "Togo"});
    this->countries.insert({"TGA", "Tonga"});
    this->countries.insert({"TRI", "Trinidad and Tobago"});
    this->countries.insert({"TUN", "Tunisia"});
    this->countries.insert({"TUR", "Turkey"});
    this->countries.insert({"TKM", "Turkmenistan"});
    this->countries.insert({"TCA", "Turks and Caicos Islands"});
    this->countries.insert({"UGA", "Uganda"});
    this->countries.insert({"UKR", "Ukraine"});
    this->countries.insert({"UAE", "United Arab Emirates"});
    this->countries.insert({"USA", "United States"});
    this->countries.insert({"URU", "Uruguay"});
    this->countries.insert({"VIR", "U.S.Virgin Islands"});
    this->countries.insert({"UZB", "Uzbekistan"});
    this->countries.insert({"VAN", "Vanuatu"});
    this->countries.insert({"VEN", "Venezuela"});
    this->countries.insert({"VIE", "Vietnam"});
    this->countries.insert({"WAL", "Wales"});
    this->countries.insert({"YEM", "Yemen"});
    this->countries.insert({"ZAM", "Zambia"});
    this->countries.insert({"ZIM", "Zimbabwe"});
  };
};

#endif // !_COUNTRY_CODES_
